/**
 * @file Interface Sync，用于接口文件生成、与wiki同步
 *
 * TODO wiki 同步功能待开发
 *
 * @author 鬼道(luics)
 * @date 2013-05-28
 */
var fs = require('fs'),
    path = require('path'),
    fm = require('util').format;

var DEFAULT_ENCODING = 'utf-8';
/**
 * 模板文件渲染
 *
 * 替换符格式
 *   {#keyword}
 *
 * @param {Object} opt
 * @param {string} opt.tplPath
 * @param {string} [opt.encoding]
 * @param {Object} [opt.data]
 * @returns {string}
 */
function render(opt) {
    var data = opt.data || {};
    var encoding = opt.encoding || DEFAULT_ENCODING;
    var tplPath = opt.tplPath;

    //版权信息
    data.ersync = data.ersync || 'Generated by if-sync';
    data.author = data.author || 'luics<luics.xu@gmail.com>';
    data.date = data.date || new Date();
    data.copyright = data.copyright || 'Copyright (c) 2013 luics';

    var source = fs.readFileSync(tplPath, encoding);

    return source.replace(/\{#(.+?)\}/g, function(match, key) {//match==$1, key==$2
        var replacer = data[key];
        return ('undefined' == typeof replacer ? '' : replacer);
    });
}

/**
 * 接口文件渲染
 *
 * @param {Object} opt
 * @param {Array} opt.files
 * @param {string} opt.title
 * @param {string} opt.basePath
 * @param {string} opt.savePath 接口文件路径
 * @param {string} [opt.encoding]
 * @param {string} [opt.extraHtml]
 */
function syncIf(opt) {
    var encoding = opt.encoding || DEFAULT_ENCODING;
    var extraHtml = opt.extraHtml || '';

    //生成数据接口文件
    var dataInc = [];
    var REQ_TOKEN = 'exports.request = ';
    var RES_TOKEN = 'exports.response = ';
    var RES_ERR_TOKEN = 'exports.responseError = ';

    for (var i = 0; i < opt.files.length; ++i) {
        var dataPath = opt.files[i] + '.js';
        var dataAbsPath = path.join(opt.basePath, dataPath);
        var data = fs.readFileSync(dataAbsPath, encoding);

        var dataFormatter = require(dataAbsPath);
        var req = dataFormatter.request;
        //var isPost = !!dataFormatter.POST;
        var isPost = true;
        var p = '/' + dataPath.replace(/\\/g, '/').replace(/\.js$/, ''); //windows path seprator
        var url = fm('%s %s', isPost ? 'POST' : 'GET', p);
        if (!isPost) {
            var qs = [];
            for (var q in req) if (req.hasOwnProperty(q)) {
                qs.push(fm('%s=%s', q, encodeURIComponent(req[q])));
            }
            url += (qs.length ? '?' + qs.join('&') : '');
        }
        
        /**
         * remove trail, add intent, remove last colon
         */
        function filter(src) {
            return src
                .replace(/^\s*|\s*$/g, '')
                //.replace(/\n/g, '\n    ')
                .replace(/\s*;$/g, '');
        }

        var end;
        end = data.indexOf(RES_TOKEN);
        var reqTxt = filter(data.substring(data.indexOf(REQ_TOKEN) + REQ_TOKEN.length, end > -1 ? end : data.length));
        end = data.indexOf(RES_ERR_TOKEN);
        var resTxt = filter(data.substring(data.indexOf(RES_TOKEN) + RES_TOKEN.length, end > -1 ? end : data.length));
        var resErrTxt = '';
        end = data.length;
        if (data.indexOf(RES_ERR_TOKEN) > -1) {
            resErrTxt = filter(data.substring(data.indexOf(RES_ERR_TOKEN) + RES_ERR_TOKEN.length, end));
        }
        //console.log(req, res);

        var cfg = dataFormatter.config || {};
        dataInc.push(render({
            tplPath: path.join(__dirname, 'data.inc.tpl'),
            data: {
                path: p,
                name: cfg.name || '-',
                desc: cfg.desc || '',
                request: reqTxt,
                response: resTxt,
                responseError: resErrTxt,
                requestUrl: url
            },
            encoding: encoding
        }));
    }

    var DATA_TPL = path.join(__dirname, 'data.tpl');
    var content = render({
        tplPath: DATA_TPL,
        data: {
            title: opt.title,
            extraHtml: extraHtml,
            content: dataInc.join('')
        },
        encoding: encoding
    })

    fs.writeFileSync(opt.savePath, content, encoding);
    console.log('Synced', opt.savePath);
}

exports.syncIf = syncIf;